//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentTypeTextNet.NKit.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentTypeTextNet.NKit.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   new group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Capture_CaptureGroup_NewGroupName {
            get {
                return ResourceManager.GetString("String_Capture_CaptureGroup_NewGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フッタ要素を隠す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Capture_InternetExplorerFooterHideTitle {
            get {
                return ResourceManager.GetString("String_Capture_InternetExplorerFooterHideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘッダ要素を隠す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Capture_InternetExplorerHeaderHideTitle {
            get {
                return ResourceManager.GetString("String_Capture_InternetExplorerHeaderHideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   new group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Finder_FindGroup_NewGroupName {
            get {
                return ResourceManager.GetString("String_Finder_FindGroup_NewGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (未選択) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Finder_FindGroup_Output_NotSelected {
            get {
                return ResourceManager.GetString("String_Finder_FindGroup_Output_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索結果: ${COUNT} 件 (${YYYY}-${MM}-${DD} ${hh24}:${mm}:${ss})
        ///ディレクトリ: ${DIR}
        ///ファイル名: ${NAME}
        ///ファイル内容: ${CONTENT} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Finder_FindGroup_Output_Title_Format {
            get {
                return ResourceManager.GetString("String_Finder_FindGroup_Output_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (非検索一致) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Finder_FindGroup_Output_Unmatched {
            get {
                return ResourceManager.GetString("String_Finder_FindGroup_Output_Unmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取消 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_View_Control_RunnableControl_CancelText {
            get {
                return ResourceManager.GetString("String_View_Control_RunnableControl_CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_View_Control_RunnableControl_RunText {
            get {
                return ResourceManager.GetString("String_View_Control_RunnableControl_RunText", resourceCulture);
            }
        }
    }
}
