//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentTypeTextNet.NKit.Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentTypeTextNet.NKit.Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] File_AcceptMessage {
            get {
                object obj = ResourceManager.GetObject("File_AcceptMessage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///        &lt;style&gt;
        ///        /* リリースノート専用スタイルシート */
        ///
        ///html {
        ///	font-family: &apos;Verdana&apos;,&apos;Meiryo UI&apos;,&apos;メイリオ&apos;, Meiryo,YuGothic,&apos;Yu Gothic&apos;,monospace;
        ///	font-size: 14pt;
        ///}
        ///
        ///body {
        ///	color: #333333;
        ///	background: #efefef;
        ///}
        ///
        ///h1 {
        ///	text-align: center;
        ///	border-bottom: 3px double #cccccc;
        ///	font-size: 140%;
        ///}
        ///
        ///section {
        ///	padding: 0 inherit 1em inherit;
        ///}
        ///
        ///h2 {
        ///	font-size: 120%;
        ///}
        ///
        ///*.version {
        ///	font-weight: bold;
        ///}
        ///
        ///*.timestamp  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_ReleaseNoteDocument {
            get {
                return ResourceManager.GetString("File_ReleaseNoteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;section&gt;
        ///	&lt;h2&gt;
        ///		&lt;strong class=&quot;vresion&quot;&gt;${VERSION}&lt;/strong&gt;
        ///		&lt;time class=&quot;timestamp&quot;&gt;${TIMESTAMP}&lt;/time&gt;
        ///	&lt;/h2&gt;
        ///	&lt;p&gt;
        ///		&lt;strong class=&quot;hash&quot;&gt;${HASH}&lt;/strong&gt;
        ///	&lt;/p&gt;
        ///	&lt;div class=&quot;view-content&quot;&gt;&lt;/div&gt;
        ///	&lt;pre class=&quot;markdown-content&quot;&gt;${CONTENT}&lt;/pre&gt;
        ///&lt;/section&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_ReleaseNoteLayout {
            get {
                return ResourceManager.GetString("File_ReleaseNoteLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Delete {
            get {
                object obj = ResourceManager.GetObject("Image_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_FolderOpen {
            get {
                object obj = ResourceManager.GetObject("Image_FolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NKit_Manager {
            get {
                object obj = ResourceManager.GetObject("NKit_Manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   更新履歴一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_About_History {
            get {
                return ResourceManager.GetString("String_About_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} にていて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_About_Title_Format {
            get {
                return ResourceManager.GetString("String_About_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用許諾 - {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Accept_Title_Format {
            get {
                return ResourceManager.GetString("String_Accept_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_ReleaseNote_NewVersion {
            get {
                return ResourceManager.GetString("String_ReleaseNote_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リリースノート - {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_ReleaseNote_Title_Format {
            get {
                return ResourceManager.GetString("String_ReleaseNote_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_TestExecute_TestState_Fail {
            get {
                return ResourceManager.GetString("String_TestExecute_TestState_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_TestExecute_TestState_None {
            get {
                return ResourceManager.GetString("String_TestExecute_TestState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_TestExecute_TestState_Ok {
            get {
                return ResourceManager.GetString("String_TestExecute_TestState_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_TestExecute_TestState_Testing {
            get {
                return ResourceManager.GetString("String_TestExecute_TestState_Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関連プログラム起動 - {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_TestExecute_Title_Format {
            get {
                return ResourceManager.GetString("String_TestExecute_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_ThirdPartyComponent_License {
            get {
                return ResourceManager.GetString("String_ThirdPartyComponent_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス URI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_ThirdPartyComponent_LicenseUri {
            get {
                return ResourceManager.GetString("String_ThirdPartyComponent_LicenseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクト URI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_ThirdPartyComponent_ProjectUri {
            get {
                return ResourceManager.GetString("String_ThirdPartyComponent_ProjectUri", resourceCulture);
            }
        }
    }
}
