//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentTypeTextNet.NKit.Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentTypeTextNet.NKit.Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] File_AcceptMessage {
            get {
                object obj = ResourceManager.GetObject("File_AcceptMessage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///        &lt;script&gt;
        ///        /**
        /// * marked - a markdown parser
        /// * Copyright (c) 2011-2014, Christopher Jeffrey. (MIT Licensed)
        /// * https://github.com/chjj/marked
        /// */
        ///
        ///;(function(root) {
        ///&apos;use strict&apos;;
        ///
        ////**
        /// * Block-Level Grammar
        /// */
        ///
        ///var block = {
        ///  newline: /^\n+/,
        ///  code: /^( {4}[^\n]+\n*)+/,
        ///  fences: noop,
        ///  hr: /^ {0,3}((?:- *){3,}|(?:_ *){3,}|(?:\* *){3,})(?:\n+|$)/,
        ///  heading: /^ *(#{1,6}) *([^\n]+?) *#* *(?:\n+|$)/,        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_ReleaseNoteDocument {
            get {
                return ResourceManager.GetString("File_ReleaseNoteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;section&gt;
        ///	&lt;h2&gt;
        ///		&lt;strong class=&quot;vresion&quot;&gt;${VERSION}&lt;/strong&gt;
        ///		&lt;time class=&quot;timestamp&quot;&gt;${TIMESTAMP}&lt;/time&gt;
        ///	&lt;/h2&gt;
        ///	&lt;p&gt;
        ///		&lt;strong class=&quot;hash&quot;&gt;${HASH}&lt;/strong&gt;
        ///	&lt;/p&gt;
        ///	&lt;div class=&quot;view-content&quot;&gt;&lt;/div&gt;
        ///	&lt;pre class=&quot;markdown-content&quot; style=&quot;display: none&quot;&gt;${CONTENT}&lt;/pre&gt;
        ///&lt;/section&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_ReleaseNoteLayout {
            get {
                return ResourceManager.GetString("File_ReleaseNoteLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NKit_Manager {
            get {
                object obj = ResourceManager.GetObject("NKit_Manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
